import pygame

SCR_W = 320
SCR_H = 180

WIN_W = 1280
WIN_H = 720

TILE_W = 8
TILE_H = 8

LEV_W = 40
LEV_H = 22

FPS = 60

LEFT = 0
RIGHT = 1
UP = 2
DOWN = 3

FULLSCREEN = False
DEBUG_MODE = False
JOY_DEADZONE = 0.4

REDUCE_DIAGONAL_SPEED = True
VARIABLE_KICK_POWER = True

WORM_MOVE_TIME = 0.2
WORM_STEPS_TIL_ADDITION = 0
WORM_INITIAL_GROW = 16

PLAYER_RESPAWN_TIME = 1.5   # in seconds
WORM_RESPAWN_TIME = 1.5
BALL_RESPAWN_TIME = 1.0
BALL_RESPAWN_TIME_AFTER_GOAL = 2.5

KEYS_LEFT = [pygame.K_LEFT, pygame.K_a]
KEYS_RIGHT = [pygame.K_RIGHT, pygame.K_d]
KEYS_UP = [pygame.K_UP, pygame.K_w]
KEYS_DOWN = [pygame.K_DOWN, pygame.K_s]
KEYS_FIRE = [pygame.K_LCTRL, pygame.K_SPACE]
