import pygame

SCR_W = 320
SCR_H = 180

WIN_W = 1280
WIN_H = 720

TILE_W = 8
TILE_H = 8

FPS = 60

LEFT = 0
RIGHT = 1
UP = 2
DOWN = 3

SPAWN_X = 75
SPAWN_Y = 90

FULLSCREEN = False
DEBUG_MODE = False
JOY_DEADZONE = 0.4

REDUCE_DIAGONAL_SPEED = True
VARIABLE_KICK_POWER = True

WORM_MOVE_TIME = 0.2
WORM_STEPS_TIL_ADDITION = 0
WORM_INITIAL_GROW = 16

PLAYER_RESPAWN_TIME = 1.5   # in seconds
WORM_RESPAWN_TIME = 1.5
BALL_RESPAWN_TIME = 1.0
BALL_RESPAWN_TIME_AFTER_GOAL = 2.5

KEYS_FIRE = [pygame.K_LCTRL, pygame.K_SPACE]
KEYS_THRUST = [pygame.K_w, pygame.K_UP]
KEYS_ROTATE_LEFT = [pygame.K_a, pygame.K_LEFT]
KEYS_ROTATE_RIGHT = [pygame.K_d, pygame.K_RIGHT]
KEYS_RESET = [pygame.K_r]

ROTATION_CHANGE = 5